### ISSUE TITLE
error[E0382]: borrow of moved value: `commit`

### ISSUE THREAD

**Issue by Mrtenz** [quilt/dahe#2]
Trying to compile the tool (`cargo build --release`, same thing happens without `--release`) results in this error message:

```
error[E0382]: borrow of moved value: `commit`
  --> src/sign.rs:31:40
   |
28 |     let commit = compute_commit(&ctx.params);
   |         ------ move occurs because `commit` has type `Vec<u8>`, which does not implement the `Copy` trait
29 |     println!("commit:\t{}", hex::encode(commit));
   |                                         ------ value moved here
30 | 
31 |     let sig = compute_sig(ctx.invoker, &commit, &pk)?;
   |                                        ^^^^^^^ value borrowed here after move

error: aborting due to previous error

For more information about this error, try `rustc --explain E0382`.
error: could not compile `dahe`
```

I'm not too familiar with Rust, so I'm not sure if I'm doing something wrong here?

**Comment by lightclient** [comment]
@Mrtenz thanks for filing an issue. Looks like a reordered a print statement and didn't realize `hex::encode(..)` was going to move the commit object. Should be good now. Please feel free to continue opening issues if you find problems.
